name: tasker_nlp
description: NLP em português para interpretação de tarefas (magic input).
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.11.5

dependencies:
  http: ^1.4.0
  meta: ^1.17.0

dev_dependencies:
  test: ^1.25.0
