/// Frases de exemplo no placeholder animado — [magicTaskInput.jsx] SUGGESTIONS.
const kMagicInputSuggestions = [
  'Levar meu pet ao veterinário amanhã',
  'Pagar o boleto do condomínio dia 5',
  'Reunião com Ana quinta às 14h',
  'Comprar presente até sexta',
  'Ir à academia às 07:30',
  'Enviar relatório hoje às 18h',
  'Marcar dentista para terça de manhã',
  'Fazer mercado sábado de tarde',
  'Ligar para o banco às 10h',
  'Pegar roupas na lavanderia amanhã às 17h',
  'Revisar orçamento dia 15/10 às 9h',
  'Comprar passagens até quarta',
  'Atualizar currículo hoje à noite',
  'Cortar o cabelo sexta às 19:30',
  'Agendar revisão do carro para segunda',
  'Buscar encomenda às 12:00 (meio-dia)',
  'Estudar inglês 1h amanhã cedo',
  'Pagar cartão até dia 02',
  'Levar notebook para conserto às 16h',
  'Reunião do projeto na próxima terça às 11h',
  'Visitar meus pais domingo à tarde',
  'Agendar exame para dia 25/09 às 08:00',
  'Fazer backup dos arquivos hoje',
  'Renovar CNH até mês que vem',
  'Entrega do cliente amanhã às 09:15',
  'Comprar gás hoje no fim da tarde',
  'Marcar aula de natação para quinta às 18h30',
  'Passear com o cachorro às 20h',
  'Organizar documentos em 3 dias',
  'Pagar internet dia 10 às 13h',
];
